{"uri":"file:///home/tarcisio/dev/phpfin/vendor/symfony/filesystem/Exception/FileNotFoundException.php","root":{"kind":0,"name":"","children":[{"kind":512,"name":"Symfony\\Component\\Filesystem\\Exception","location":[11,0,11,49]},{"kind":1,"name":"Symfony\\Component\\Filesystem\\Exception\\FileNotFoundException","location":[19,0,33,1],"associated":[{"kind":1,"name":"Symfony\\Component\\Filesystem\\Exception\\IOException"}],"description":"Exception class thrown when a file couldn't be found.","children":[{"kind":32,"name":"__construct","modifiers":1,"location":[21,4,32,5],"scope":"Symfony\\Component\\Filesystem\\Exception\\FileNotFoundException","children":[{"kind":128,"name":"$message","location":[21,32,21,47],"scope":"__construct","value":"null"},{"kind":128,"name":"$code","location":[21,49,21,58],"scope":"__construct","value":"0"},{"kind":128,"name":"$previous","location":[21,60,21,87],"scope":"__construct","value":"null","typeSource":1,"type":"Exception"},{"kind":128,"name":"$path","location":[21,89,21,101],"scope":"__construct","value":"null"}]}]}]}}