{"uri":"file:///home/tarcisio/dev/phpfin/vendor/illuminate/database/DetectsLostConnections.php","root":{"kind":0,"name":"","children":[{"kind":512,"name":"Illuminate\\Database","location":[2,0,2,30]},{"kind":1,"name":"Exception","modifiers":4096,"location":[4,4,4,13],"associated":[{"kind":1,"name":"Exception"}]},{"kind":1,"name":"Str","modifiers":4096,"location":[5,4,5,26],"associated":[{"kind":1,"name":"Illuminate\\Support\\Str"}]},{"kind":4,"name":"Illuminate\\Database\\DetectsLostConnections","location":[7,0,32,1],"children":[{"kind":32,"name":"causedByLostConnection","modifiers":2,"location":[15,4,31,5],"description":"Determine if the given exception was caused by a lost connection.","scope":"Illuminate\\Database\\DetectsLostConnections","type":"bool","children":[{"kind":128,"name":"$e","location":[15,46,15,58],"scope":"causedByLostConnection","typeSource":1,"type":"Exception"}]}]}]}}