{"uri":"file:///home/tarcisio/dev/phpfin/vendor/symfony/yaml/Exception/RuntimeException.php","root":{"kind":0,"name":"","children":[{"kind":512,"name":"Symfony\\Component\\Yaml\\Exception","location":[11,0,11,43]},{"kind":1,"name":"Symfony\\Component\\Yaml\\Exception\\RuntimeException","location":[18,0,20,1],"associated":[{"kind":1,"name":"RuntimeException"},{"kind":2,"name":"Symfony\\Component\\Yaml\\Exception\\ExceptionInterface"}],"description":"Exception class thrown when an error occurs during parsing."}]}}